import { useState } from "react";
import { Helmet } from "react-helmet-async";
import { Briefcase, Filter, Search } from "lucide-react";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { usePortfolio } from "@/hooks/usePortfolio";
import { PortfolioStats } from "@/components/portfolio/PortfolioStats";
import { PortfolioTable } from "@/components/portfolio/PortfolioTable";
import { AddDomainDialog } from "@/components/portfolio/AddDomainDialog";
import { BulkImportDialog } from "@/components/portfolio/BulkImportDialog";

export default function Portfolio() {
  const { domains, loading, stats, addDomain, updateDomain, deleteDomain, refreshValuation, bulkAddDomains } = usePortfolio();
  const [search, setSearch] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");

  const filtered = domains.filter((d) => {
    const matchesSearch = d.domain_name.toLowerCase().includes(search.toLowerCase());
    const matchesStatus = statusFilter === "all" || d.status === statusFilter;
    return matchesSearch && matchesStatus;
  });

  return (
    <>
      <Helmet>
        <title>Portfolio | ExpiredHawk</title>
        <meta name="description" content="Track your domain portfolio with P&L, valuations, and renewal costs." />
      </Helmet>
      <Navbar />
      <main className="min-h-screen pt-24 pb-16 bg-background">
        <div className="container mx-auto px-4 space-y-6">
          {/* Header */}
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-primary/10">
                <Briefcase className="w-6 h-6 text-primary" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-foreground">Portfolio</h1>
                <p className="text-sm text-muted-foreground">
                  {stats.totalDomains} domain{stats.totalDomains !== 1 ? "s" : ""} · {stats.totalSold} sold
                </p>
              </div>
            </div>
            <div className="flex items-center gap-2">
              <BulkImportDialog onBulkAdd={bulkAddDomains} />
              <AddDomainDialog onAdd={addDomain} />
            </div>
          </div>

          {/* Stats */}
          <PortfolioStats stats={stats} />

          {/* Search & Filter */}
          <div className="flex flex-col sm:flex-row gap-3">
            <div className="relative flex-1">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
              <Input
                placeholder="Search domains..."
                className="pl-9"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
            </div>
            <Select value={statusFilter} onValueChange={setStatusFilter}>
              <SelectTrigger className="w-[160px]">
                <Filter className="w-4 h-4 mr-2" />
                <SelectValue placeholder="All statuses" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Statuses</SelectItem>
                <SelectItem value="holding">Holding</SelectItem>
                <SelectItem value="listed">Listed</SelectItem>
                <SelectItem value="developing">Developing</SelectItem>
                <SelectItem value="parked">Parked</SelectItem>
                <SelectItem value="sold">Sold</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Table */}
          {loading ? (
            <div className="text-center py-12 text-muted-foreground">Loading portfolio...</div>
          ) : (
            <PortfolioTable
              domains={filtered}
              onUpdate={updateDomain}
              onDelete={deleteDomain}
              onRefreshValuation={refreshValuation}
            />
          )}

          {/* Disclaimer */}
          <p className="text-[10px] text-muted-foreground text-center">
            Valuations are estimates generated by ExpiredHawk's algorithm. They are not appraisals and should not be the sole basis for investment decisions.
          </p>
        </div>
      </main>
      <Footer />
    </>
  );
}
